int8 portDriveEncoder = 0
int8 starboardDriveEncoder = 1
int8 depWinchEncoder = 2
int8 bcBeltEncoder = 3
int8 bcTranslationEncoder = 4
int8 bcAttitudePortPot = 5
int8 bcAttitudeStarboardPot = 6
int8 portLookyEncoder = 7
int8 starboardLookyEncoder = 8
int8 depPortLoadCell = 9
int8 depStarboardLoadCell = 10
int8 gyro0X = 11
int8 gyro0Y = 12
int8 gyro0Z = 13
int8 accel0X = 14
int8 accel0Y = 15
int8 accel0Z = 16
int8 gyro1X = 17
int8 gyro1Y = 18
int8 gyro1Z = 19
int8 accel1X = 20
int8 accel1Y = 21
int8 accel1Z = 22
int8 depLowerLimit = 23
int8 depUpperLimit = 24
int8 excForeLimit = 25
int8 excAftLimit = 26
int8 bcLowerLimit = 27
int8 bcUpperLimit = 28
int8 eStop = 29
int8 angDisplacementX = 30
int8 angDisplacementY = 31
int8 angdisplacementZ = 32

int8 sensorID
float64 value