<?xml version="1.0"?>
<robot name="glennobi" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find glennobi_description)/urdf/glennobi.gazebo.xacro"/>
    <xacro:include filename="$(find glennobi_description)/urdf/glennobi.transmission.xacro"/>


    <!-- Units in Meters-->
    <xacro:property name="bodylength" value="0.9411"/>
    <xacro:property name="bodywidth" value="0.4577"/>
    <xacro:property name="bodyheight" value="0.477"/>
    <xacro:property name="wheelradius" value="0.1642"/>
    <xacro:property name="wheelwidth" value="0.0635"/>
    <!-- Distance from the centers of the wheels in the length and width of robot. -->
    <!-- wheelsepx crosses through the robot -->
    <xacro:property name="wheelsepx" value="0.3874"/>
    <!-- wheelsepy is from wheel to wheel not crossing the center line-->
    <xacro:property name="wheelsepy" value="0.386"/>
    <!-- If wheels are not aligned use offset-->
    <xacro:property name="wheeloffsetx" value="0.0"/>

    <!-- body is for aligning the robot mesh to the center of gravity-->
    <!-- Data from cad model 
    X = -2.54667
	Y = 0.68615
	Z = 9.90497
    Note not currently used but leaving here because might be useful later-->
    <xacro:property name="bodyx" value="0"/>
    <xacro:property name="bodyy" value="0"/>
    <xacro:property name="bodyz" value="-0.05"/>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
          <mass value="${mass}"/>
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel" params="prefix side reflect">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheelradius}" length="${wheelwidth}"/>
                </geometry>
            </visual>
            <collision>
                <!-- cylinder origin different than mesh origin -->
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheelradius}" length="${wheelwidth}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="1.6"/>
                <inertia ixx="0.035" ixy="0.0" ixz="0.0" iyy="0.035" iyz="0.0" izz="0.06" />
            </inertial>
        </link>
        
        <!-- set gazebo wheel properties -->
        <xacro:wheel_gazebo prefix="${prefix}"/>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${side*wheelsepx + wheeloffsetx} ${reflect*(wheelsepy/2 + wheelwidth/2)} 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.8" friction="2.0"/>
        </joint>
        
        <!-- set wheel transmission properties -->
        <xacro:wheel_transmission prefix="${prefix}"/>
        
    </xacro:macro>

    <link name="base_link">
        <visual>
            <origin xyz="${bodyx} ${bodyy} ${bodyz}" rpy="0 0 ${pi/2}"/>
            <geometry>
                    <mesh filename="package://glennobi_description/meshes/chassis.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="${bodyx} 0 ${bodyz}" rpy="${pi/2} 0 ${pi/2}"/>
            <geometry>
                <mesh filename="package://glennobi_description/meshes/chassis.dae"/>
                <!-- box size="${bodylength} ${bodywidth} ${bodyheight}"/-->
            </geometry>
        </collision>
        <inertial>
            <mass value="16"/>
            <inertia ixx="4.5" ixy="0.0" ixz="0.0" iyy="4.5" iyz="0.0" izz="0.8" />
        </inertial>
    </link>

    <xacro:wheel prefix="front_right" side="1" reflect="-1"/>
    <xacro:wheel prefix="front_left" side="1" reflect="1"/>
    <xacro:wheel prefix="back_right" side="-1" reflect="-1"/>
    <xacro:wheel prefix="back_left" side="-1" reflect="1"/>

    <link name="realsense_link">
        <visual>
            <geometry>
                <box size="0.1 0.025 0.015"/>
            </geometry>
        </visual>
    </link>

    <joint name="realsense_joint" type="fixed">
        <parent link="base_link"/>
        <child link="realsense_link"/>
        <!-- transform from base_link with additional 20 degree tilt down -->
        <origin xyz="-0.57 0 0.33" rpy="${-(20+90)*pi/180} 0 ${pi/2}"/>
    </joint>

    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.35 -0.1 0" rpy="0 0 0"/>
    </joint>

</robot>
