type: "diff_drive_controller/DiffDriveController"
publish_rate: 30
left_wheel: ['front_left_wheel_joint', 'back_left_wheel_joint']
right_wheel: ['front_right_wheel_joint', 'back_right_wheel_joint']

pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist_covariance_diagonal: [0.002, 0.02, 0.0, 0.0, 0.0, 0.001]

enable_odom_tf: false

wheel_separation_multiplier: 3

linear:
    x:
        has_acceleration_limits: true
        max_acceleration       : 3.0  # m/s^2
angular:
    z:
        has_acceleration_limits: true
        max_acceleration       : 6.0  # rad/s^2
